### ISSUE TITLE
once outcome doesn't have tie, use that instead of maybe plaher

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-tic-tac-iffffy#3]
https://github.com/TU-CSCI2322-FL22/solver-tic-tac-iffffy/blob/6f53f05c39749a03e98177c8e9479142ea1a8cc5/tic-tac-iffffy.hs#L11

**Comment by lucypham951** [comment]
changed Miniboard data to 
newtype MiniBoard = Game [Cell] deriving (Show, Eq) --Miniboard will be a bunch of cells
