### ISSUE TITLE
Makemove definitely takes a move, don't need the maybe.

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-tic-tac-iffffy#5]
https://github.com/TU-CSCI2322-FL22/solver-tic-tac-iffffy/blob/6f53f05c39749a03e98177c8e9479142ea1a8cc5/tic-tac-iffffy.hs#L41-L43

**Comment by sfogarty** [comment]
But for full credit, you should RETURN a maybe in case hte move is invalid

**Comment by Matvezy** [comment]
Solved
