### ISSUE TITLE
Don't make custom shows, just show functions

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-tic-tac-iffffy#9]
https://github.com/TU-CSCI2322-FL22/solver-tic-tac-iffffy/blob/6f53f05c39749a03e98177c8e9479142ea1a8cc5/tic-tac-iffffy.hs#L73-L75

**Comment by sfogarty** [comment]
for instance, make this showPlayer instead.

**Comment by sfogarty** [comment]
Or, don't use "show" on player at all, and just have "showFor" pattern match Cricle or Cross.

**Comment by Matvezy** [comment]
Solved
